# Generated by Django 4.2.23 on 2025-06-25 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marca si contiene información sensible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('compliance_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=50)),
                ('dmarc_policy', models.CharField(choices=[('none', 'None'), ('quarantine', 'Quarantine'), ('reject', 'Reject')], default='none', max_length=20)),
                ('dns_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('dns_provider_zone_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_dns_check', models.DateTimeField(blank=True, null=True)),
                ('dns_check_status', models.CharField(default='pending', max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notify_on_changes', models.BooleanField(default=True)),
                ('notify_on_expiration', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='accounts.empresa')),
                ('tags', models.ManyToManyField(blank=True, related_name='dominios', to='panel.tag')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
                'ordering': ['-creado_en'],
                'unique_together': {('nombre', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('dns_check', 'DNS Check'), ('bulk_operation', 'Bulk Operation')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('SPF', 'SPF'), ('DKIM', 'DKIM'), ('DMARC', 'DMARC'), ('MX', 'MX'), ('TXT', 'TXT'), ('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME')], max_length=10)),
                ('nombre', models.CharField(help_text='Nombre del registro (ej: @, www, mail)', max_length=255)),
                ('valor', models.TextField()),
                ('ttl', models.PositiveIntegerField(default=3600, help_text='Time To Live en segundos')),
                ('prioridad', models.PositiveIntegerField(blank=True, help_text='Solo para registros MX', null=True)),
                ('estado', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('pending', 'Pending'), ('error', 'Error'), ('warning', 'Warning')], default='pending', max_length=50)),
                ('ultima_comprobacion', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('selector', models.CharField(blank=True, help_text='Solo para DKIM', max_length=100, null=True)),
                ('policy', models.CharField(blank=True, help_text='Solo para DMARC', max_length=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='panel.dominio')),
            ],
            options={
                'verbose_name': 'Registro DNS',
                'verbose_name_plural': 'Registros DNS',
                'ordering': ['-actualizado_en'],
                'unique_together': {('dominio', 'tipo', 'nombre')},
            },
        ),
    ]
