# Generated by Django 4.2.23 on 2025-06-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroDNS',
            new_name='DNSRecord',
        ),
    ]
