# Generated by Django 4.2.23 on 2025-06-24 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('panel', '0002_rename_registrodns_dnsrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='dnsrecord',
            options={'ordering': ['-actualizado_en'], 'verbose_name': 'Registro DNS', 'verbose_name_plural': 'Registros DNS'},
        ),
        migrations.AlterModelOptions(
            name='dominio',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Dominio', 'verbose_name_plural': 'Dominios'},
        ),
        migrations.AlterModelOptions(
            name='dominiousuarioacceso',
            options={'verbose_name': 'Acceso de Usuario a Dominio', 'verbose_name_plural': 'Accesos de Usuarios a Dominios'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nombre'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='nombre',
            field=models.CharField(default='2025-06-01 00:00:00', help_text='Nombre del registro (ej: @, www, mail)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='policy',
            field=models.CharField(blank=True, help_text='Solo para DMARC', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='prioridad',
            field=models.PositiveIntegerField(blank=True, help_text='Solo para registros MX', null=True),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='selector',
            field=models.CharField(blank=True, help_text='Solo para DKIM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='ttl',
            field=models.PositiveIntegerField(default=3600, help_text='Time To Live en segundos'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='dns_check_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='dominio',
            name='dns_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='dns_provider_zone_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='last_dns_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='notify_on_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='notify_on_expiration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dominio',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dominiousuarioacceso',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dominiousuarioacceso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='estado',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('pending', 'Pending'), ('error', 'Error'), ('warning', 'Warning')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='tipo',
            field=models.CharField(choices=[('SPF', 'SPF'), ('DKIM', 'DKIM'), ('DMARC', 'DMARC'), ('MX', 'MX'), ('TXT', 'TXT'), ('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dominiousuarioacceso',
            name='dominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='panel.dominio'),
        ),
        migrations.AlterField(
            model_name='dominiousuarioacceso',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='dominiousuarioacceso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dnsrecord',
            unique_together={('dominio', 'tipo', 'nombre')},
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marca si contiene información sensible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('dns_check', 'DNS Check'), ('bulk_operation', 'Bulk Operation')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
