# Generated by Django 4.2.23 on 2025-06-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_company', models.CharField(blank=True, max_length=255, null=True)),
                ('compliance_level', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SPF', 'SPF'), ('DKIM', 'DKIM'), ('DMARC', 'DMARC')], max_length=10)),
                ('value', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('selector', models.CharField(blank=True, max_length=100, null=True)),
                ('policy', models.CharField(blank=True, max_length=10, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='domains.domain')),
            ],
        ),
    ]
